import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { FileText, Download, Shield, CheckCircle, AlertTriangle, XCircle } from 'lucide-react'
import { getDashboardSummary } from '../lib/api'
import { format } from 'date-fns'

const ORG_ID = localStorage.getItem('glasslm_org_id') ?? ''

const FRAMEWORKS = [
  { id: 'gdpr', name: 'GDPR', region: 'EU', color: 'text-blue-400' },
  { id: 'soc2', name: 'SOC 2 Type II', region: 'US', color: 'text-purple-400' },
  { id: 'hipaa', name: 'HIPAA', region: 'US Healthcare', color: 'text-green-400' },
  { id: 'iso27001', name: 'ISO 27001', region: 'International', color: 'text-yellow-400' },
]

export default function Reports() {
  const [generating, setGenerating] = useState<string | null>(null)

  const { data } = useQuery({
    queryKey: ['dashboard', ORG_ID, 30],
    queryFn: () => getDashboardSummary(ORG_ID, 30),
    enabled: !!ORG_ID,
  })

  const totalMasked = data?.events_with_pii ?? 0
  const totalBlocked = data?.blocked ?? 0
  const avgRisk = data?.avg_risk ?? 0
  const complianceScore = Math.max(0, 100 - avgRisk * 8)

  function generateReport(frameworkId: string) {
    setGenerating(frameworkId)

    const lines = [
      `GlassLM AI Privacy Compliance Report`,
      `Framework: ${FRAMEWORKS.find((f) => f.id === frameworkId)?.name}`,
      `Generated: ${format(new Date(), 'PPP')}`,
      `Report Period: Last 30 days`,
      ``,
      `SUMMARY`,
      `───────────────────────────────`,
      `Total AI Interactions:     ${data?.total_events ?? 0}`,
      `Interactions with PII:     ${totalMasked}`,
      `PII Masking Rate:          ${data?.total_events ? Math.round((totalMasked / data.total_events) * 100) : 0}%`,
      `Interactions Blocked:      ${totalBlocked}`,
      `Average Risk Score:        ${avgRisk}/10`,
      `Compliance Score:          ${complianceScore}/100`,
      ``,
      `PII TYPES DETECTED (30 days)`,
      `───────────────────────────────`,
      ...Object.entries(data?.type_counts ?? {}).map(
        ([type, count]) => `${type.padEnd(25)} ${count}`
      ),
      ``,
      `AI PROVIDERS USED`,
      `───────────────────────────────`,
      ...Object.entries(data?.provider_counts ?? {}).map(
        ([p, c]) => `${p.padEnd(25)} ${c} calls`
      ),
      ``,
      `PRIVACY CONTROLS IN PLACE`,
      `───────────────────────────────`,
      `✓ Client-side PII detection and masking`,
      `✓ Zero message content stored on servers`,
      `✓ Metadata-only logging (masked types + counts)`,
      `✓ Policy enforcement (warn/block/redact)`,
      `✓ Audit trail for all AI interactions`,
      `✓ User hashing (SHA-256) for privacy`,
      ``,
      `This report was generated by GlassLM — AI Privacy Infrastructure`,
      `https://glasslm.space`,
    ].join('\n')

    const blob = new Blob([lines], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `glasslm-${frameworkId}-report-${format(new Date(), 'yyyy-MM-dd')}.txt`
    a.click()
    URL.revokeObjectURL(url)

    setTimeout(() => setGenerating(null), 1000)
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Compliance Reports</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Download AI privacy audit reports for compliance frameworks.
        </p>
      </div>

      {/* Compliance score */}
      <div className="glass-card p-6 rounded-2xl">
        <div className="flex items-center gap-6">
          <div className="relative w-24 h-24 flex-shrink-0">
            <svg className="w-24 h-24 -rotate-90" viewBox="0 0 96 96">
              <circle cx="48" cy="48" r="40" fill="none" stroke="hsl(270 20% 18%)" strokeWidth="8" />
              <circle cx="48" cy="48" r="40" fill="none"
                stroke={complianceScore >= 80 ? 'hsl(145 60% 45%)' : complianceScore >= 50 ? 'hsl(38 92% 50%)' : 'hsl(0 70% 55%)'}
                strokeWidth="8"
                strokeDasharray={`${(complianceScore / 100) * 251} 251`}
                strokeLinecap="round" />
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="text-xl font-bold font-mono text-foreground">{complianceScore}</span>
            </div>
          </div>
          <div>
            <p className="text-sm font-medium text-muted-foreground uppercase tracking-wider">Privacy Compliance Score</p>
            <p className="text-2xl font-bold text-foreground mt-1">{complianceScore}/100</p>
            <p className="text-xs text-muted-foreground mt-1">Based on 30-day AI usage patterns</p>
            <div className="flex items-center gap-4 mt-3 text-xs">
              <span className="flex items-center gap-1 text-green-400"><CheckCircle className="w-3 h-3" /> PII Masking Active</span>
              <span className="flex items-center gap-1 text-green-400"><CheckCircle className="w-3 h-3" /> Audit Logging On</span>
              {totalBlocked > 0 && (
                <span className="flex items-center gap-1 text-yellow-400"><AlertTriangle className="w-3 h-3" /> {totalBlocked} Blocked</span>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Framework reports */}
      <div className="grid grid-cols-2 gap-4">
        {FRAMEWORKS.map((fw) => (
          <div key={fw.id} className="glass-card p-6 rounded-2xl">
            <div className="flex items-start justify-between mb-4">
              <div>
                <p className={`text-sm font-bold ${fw.color}`}>{fw.name}</p>
                <p className="text-xs text-muted-foreground">{fw.region}</p>
              </div>
              <div className="p-2 rounded-lg bg-card/60">
                <Shield className="w-4 h-4 text-muted-foreground" />
              </div>
            </div>
            <div className="space-y-2 mb-5 text-xs text-muted-foreground">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-3 h-3 text-green-400" />
                AI data processing documented
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-3 h-3 text-green-400" />
                PII minimization in effect
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="w-3 h-3 text-green-400" />
                Audit trail maintained
              </div>
              <div className="flex items-center gap-2">
                {avgRisk < 5
                  ? <CheckCircle className="w-3 h-3 text-green-400" />
                  : <XCircle className="w-3 h-3 text-yellow-400" />}
                Risk score acceptable
              </div>
            </div>
            <button onClick={() => generateReport(fw.id)} disabled={generating === fw.id}
              className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl border border-border/60 text-sm font-medium hover:bg-primary/10 hover:border-primary/40 hover:text-primary transition-all disabled:opacity-50">
              <Download className="w-4 h-4" />
              {generating === fw.id ? 'Generating...' : 'Download Report'}
            </button>
          </div>
        ))}
      </div>

      <div className="glass-card p-5 rounded-xl flex items-start gap-3 border border-primary/20">
        <FileText className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
        <p className="text-xs text-muted-foreground">
          Reports are generated from your 30-day event metadata. No message content is ever stored or included.
          For enterprise custom reports or legal attestation letters, <a href="mailto:hello@glasslm.space" className="text-primary hover:underline">contact us</a>.
        </p>
      </div>
    </div>
  )
}
